config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'pages#landing'
  get '/about',   to: 'pages#about'
  get '/contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 144 }
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def landing
    @post = Post.last
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
    @post = set_post
  end

  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post ||= set_post
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "Post published successfully"
      redirect_to @post
    else
      flash[:error] = "Something went wrong"
      render action: 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render action :update
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def set_title(title)
    base = 'MH Blog'
    return title.capitalize + ' | ' +  base
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/partials/head' %>
  <body class="Grid">
    <%= render 'layouts/partials/flash' %>
    <%= render 'layouts/partials/header' %>
    <main class="Grid-mainContainer">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="Grid-mainContainer Flash Flash-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/partials/_head.html.erb
<head>
  <title><%= yield :title %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Arimo" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/partials/_header.html.erb
<header class="Header Grid-mainContainer">
  <div>
    <h1>Scope Change</h1>
  </div>
  <nav class="Header-anchorContainer">
    <%= link_to "blog", root_path, class: "Header-anchorTag" %>
    <%= link_to "about", about_path, class: "Header-anchorTag" %>
    <%= link_to "contact", contact_path, class: "Header-anchorTag" %>
  </nav>
</header>

app/views/pages/about.html.erb
<% provide(:title, set_title("about")) %>

<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, set_title("contact")) %>

<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/landing.html.erb
<% provide(:title, "MH Blog") %>

<%= @post.title %>
<%= @post.body %>

app/views/posts/_post_form.html.erb
<%= form_for(@post, html: {class: 'Form'}) do |f| %>
  <%= f.label :title, class: 'Form-label' %>
  <%= f.text_field :title %>
  <%= f.label :body, class: 'Form-label' %>
  <%= f.text_area :body, class: 'Form-textArea Form-textArea--100pct' %>
  <%= f.label :draft, "Save as draft", class: 'Form-label Form-label--inline' %>
  <%= f.check_box :draft %>
  <%= f.submit "Publish", class: 'Form-submitBtn' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'post_form' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'post_form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= @post.title %>
<%= @post.body %>
<%= @post.created_at %>

<%= link_to 'Edit', edit_post_path(@post) %> |